In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r'C:\FBS\Data Analysis\Dataexploration\50_Startups.csv')

In [3]:
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
df.describe()

           R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [5]:
df.isna().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [6]:
df.info

<bound method DataFrame.info of     R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40>

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     str
 4   Profit           50 non-null     float64
dtypes: float64(4), str(1)
memory usage: 2.1 KB

In [8]:
df['State'].unique()

<StringArray>
['New York', 'California', 'Florida']
Length: 3, dtype: str

In [9]:
df_state=pd.get_dummies(df['State'],dtype='int')

In [10]:
df=pd.concat([df,df_state],axis=1)

In [11]:
df.head()

,R&D Spend,Administration,Marketing Spend,State,Profit,California,Florida,New York
0,165349.20,136897.80,471784.10,New York,192261.83,0,0,1
1,162597.70,151377.59,443898.53,California,191792.06,1,0,0
2,153441.51,101145.55,407934.54,Florida,191050.39,0,1,0
3,144372.41,118671.85,383199.62,New York,182901.99,0,0,1
4,142107.34,91391.77,366168.42,Florida,166187.94,0,1,0

In [12]:
df.head()

,R&D Spend,Administration,Marketing Spend,State,Profit,California,Florida,New York
0,165349.20,136897.80,471784.10,New York,192261.83,0,0,1
1,162597.70,151377.59,443898.53,California,191792.06,1,0,0
2,153441.51,101145.55,407934.54,Florida,191050.39,0,1,0
3,144372.41,118671.85,383199.62,New York,182901.99,0,0,1
4,142107.34,91391.77,366168.42,Florida,166187.94,0,1,0

In [13]:
df.drop('State',axis=1,inplace=True)

In [14]:
df.head()

,R&D Spend,Administration,Marketing Spend,Profit,California,Florida,New York
0,165349.20,136897.80,471784.10,192261.83,0,0,1
1,162597.70,151377.59,443898.53,191792.06,1,0,0
2,153441.51,101145.55,407934.54,191050.39,0,1,0
3,144372.41,118671.85,383199.62,182901.99,0,0,1
4,142107.34,91391.77,366168.42,166187.94,0,1,0

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
min_max=MinMaxScaler()

In [18]:
#min_max scaling returns an array not a dataframe
result=min_max.fit_transform(df[['R&D Spend','Administration','Marketing Spend','Profit']])

In [19]:
result

array([[1.        , 0.65174393, 1.        , 1.        ],
       [0.98335946, 0.76197173, 0.94089337, 0.99735461],
       [0.92798459, 0.37957895, 0.8646636 , 0.99317808],
       [0.87313643, 0.51299839, 0.81223513, 0.94729239],
       [0.85943772, 0.30532804, 0.77613557, 0.85317138],
       [0.797566  , 0.3694479 , 0.76912588, 0.80138177],
       [0.81412828, 0.73016111, 0.27071031, 0.79649041],
       [0.7880179 , 0.71745725, 0.68649342, 0.79440736],
       [0.72901786, 0.74173276, 0.66049977, 0.77446805],
       [0.74590551, 0.43692884, 0.64644319, 0.7606613 ],
       [0.61635061, 0.45150637, 0.48573267, 0.74017475],
       [0.60884455, 0.30836422, 0.52936195, 0.72968626],
       [0.56766982, 0.57883556, 0.52956308, 0.71462897],
       [0.55635219, 0.64106561, 0.53555202, 0.67364377],
       [0.72539353, 0.8013272 , 0.54370828, 0.66404417],
       [0.69261666, 0.54302973, 0.55486446, 0.64892083],
       [0.47180821, 0.53527036, 0.56031151, 0.63245443],
       [0.57246821, 0.71401273, 0.59894835, 0.62331739],
       [0.55488118, 0.47877201, 0.62511553, 0.61710347],
       [0.52264964, 0.77823604, 0.        , 0.60871268],
       [0.46116861, 0.47642362, 0.63305328, 0.58448237],
       [0.47408436, 0.78021012, 0.63532724, 0.54415692],
       [0.4475048 , 0.54429273, 0.64291963, 0.53874658],
       [0.40842369, 0.4146383 , 0.64599195, 0.52963376],
       [0.46594728, 0.3653876 , 0.29796428, 0.52860915],
       [0.39107967, 0.67195793, 0.29242745, 0.52214616],
       [0.45557444, 0.70684477, 0.28413435, 0.51273747],
       [0.43609283, 0.58297807, 0.74861321, 0.50865352],
       [0.39946683, 1.        , 0.25042853, 0.49893437],
       [0.39676926, 0.77456642, 0.22709197, 0.48610784],
       [0.37493063, 0.48992809, 0.19316302, 0.48009902],
       [0.36974101, 0.77205322, 0.18698856, 0.46627976],
       [0.38348453, 0.5932935 , 0.09768292, 0.46596599],
       [0.33561668, 0.39413365, 0.45494286, 0.46231175],
       [0.2807759 , 0.81005496, 0.44680961, 0.46193942],
       [0.2782839 , 0.25703165, 0.43561799, 0.4606257 ],
       [0.17335288, 0.57682456, 0.42631115, 0.42812595],
       [0.26652654, 0.        , 0.41762624, 0.42385155],
       [0.12234465, 0.11163611, 0.39269043, 0.37474659],
       [0.23319442, 0.24130912, 0.3709309 , 0.37348913],
       [0.17390063, 0.51204073, 0.36626005, 0.35791393],
       [0.16869099, 0.25446874, 0.34861436, 0.3554301 ],
       [0.14297577, 0.34185188, 0.31370517, 0.3199513 ],
       [0.09377566, 0.57930693, 0.07531871, 0.31015569],
       [0.13412668, 0.78807166, 0.06005866, 0.28448478],
       [0.0060492 , 0.5547241 , 0.0040356 , 0.28294041],
       [0.00795565, 0.49125975, 0.62976785, 0.19602019],
       [0.        , 0.64054682, 0.        , 0.15698988],
       [0.00327821, 0.00350184, 0.        , 0.11821128],
       [0.        , 0.50014806, 0.09574943, 0.        ]])

In [24]:
df_result=pd.DataFrame(result,columns=['R&D Spend','Administration','Marketing Spend','Profit'])

In [25]:
df_result.head()

   R&D Spend  Administration  Marketing Spend    Profit
0   1.000000        0.651744         1.000000  1.000000
1   0.983359        0.761972         0.940893  0.997355
2   0.927985        0.379579         0.864664  0.993178
3   0.873136        0.512998         0.812235  0.947292
4   0.859438        0.305328         0.776136  0.853171

In [26]:
df=df.drop(['R&D Spend','Administration','Marketing Spend','Profit'],axis=1)
df_final=pd.concat([df_result,df],axis=1)

In [27]:
df_finale.head()

NameError: name 'df_finale' is not defined

In [30]:
df_final.head()

,R&D Spend,Administration,Marketing Spend,Profit,California,Florida,New York
0,1.000000,0.651744,1.000000,1.000000,0,0,1
1,0.983359,0.761972,0.940893,0.997355,1,0,0
2,0.927985,0.379579,0.864664,0.993178,0,1,0
3,0.873136,0.512998,0.812235,0.947292,0,0,1
4,0.859438,0.305328,0.776136,0.853171,0,1,0

In [31]:
X=df_final.drop('Profit',axis=1)
y=df_final['Profit']

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [33]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [34]:
m=regressor.coef_
c=regressor.intercept_

In [35]:
print(m,c)

[ 0.75014058 -0.05088479  0.07931799 -0.00177531  0.00351127 -0.00173596] 0.20348098747221566

In [36]:
#we cannot plot a graph for multiple linear regression

In [37]:
y_train_predict=regressor.predict(x_train)
y_test_predict=regressor.predict(x_test)

In [38]:
from sklearn.metrics import root_mean_squared_error,mean_squared_error,mean_absolute_error,mean_absolute_percentage_error
print("rmse=",root_mean_squared_error(y_train,y_train_predict))
print("mse=",mean_squared_error(y_train,y_train_predict))
print("mae=",mean_absolute_error(y_train,y_train_predict))
print("mape=",mean_absolute_percentage_error(y_train,y_train_predict))

rmse= 0.0502729327398298
mse= 0.002527367766263451
mae= 0.03751909059408802
mape= 20699715050097.555

In [39]:
#r2 score says how well thw model is

In [42]:
from sklearn.metrics import r2_score
print("r2_score=",r2_score(y_train,y_train_predict))# near 1 so best model

r2_score= 0.9537019995248526